yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

import textwrap


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return textwrap.shorten(self.text, width=15, placeholder='...')


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Комментарий',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Запись: '{self.post}', автор: '{self.author}'"


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='one_following'),
            models.CheckConstraint(check=~models.Q(user=models.F('author')),
                                   name='user_not_author')
        ]

yatube/posts/forms.py
from django import forms
from django.utils.safestring import mark_safe

from .models import Post, Group, Comment


class PostForm(forms.ModelForm):
    text = forms.CharField(label='Текст поста',
                           max_length=200, widget=forms.Textarea,
                           help_text=mark_safe
                           ("Пожалуйста, введите полный текст поста."))
    group = forms.ModelChoiceField(label='Группа',
                                   queryset=Group.objects.all(),
                                   required=False,
                                   help_text=mark_safe
                                   ("Пожалуйста, выберите группу."))

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {'text': 'My help_text',
                      'group': 'My help_text for group'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Group, Post, Follow
from .forms import PostForm, CommentForm

MAX_POSTS = 10


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    page_obj = paginator(request, posts)
    title = 'Последние обновления на сайте'
    context = {
        'posts': posts,
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator(request, posts)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    post_count = posts.count()
    user = request.user
    following = user.is_authenticated and author.following.exists()
    if user.is_authenticated:
        if Follow.objects.filter(
            user=request.user,
            author=author,
        ).exists():
            following = True
    page_obj = paginator(request, posts)
    context = {
        'post_count': post_count,
        'posts': posts,
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_count = Post.objects.filter(author=post.author).count()
    group = post.group
    form = CommentForm(request.POST)
    comments = post.comments.all()
    context = {
        'post': post,
        'post_count': post_count,
        'group': group,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if request.method == "POST":
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    if request.method == "POST":
        if form.is_valid():
            post = form.save()
            form.save()
            return redirect('posts:post_detail', post_id)
    return render(request, 'posts/create_post.html', {'form': form})


def paginator(request, posts):
    paginator = Paginator(posts, MAX_POSTS)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    post_count = posts.count()
    page_obj = paginator(request, posts)
    context = {
        'page_obj': page_obj,
        'post_count': post_count,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(
        user=request.user,
        author=author,
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}    
  {% if form.instance.id %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}    
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if form.instance.id %}
              Редактирование поста
            {% else %}
              Новый пост  
            {% endif %}             
          </div>
            <div class="card-body">
              {% if form.errors %}
                  {% for field in form %}                   
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}          
              <form method="post" enctype="multipart/form-data" 
              {% if action %}
                action="{% url 'posts:post_create' %}"
              {% endif %}>
              {% csrf_token %}
              {% for field in form %}
                {% if field.help_text %}
                  <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}                  
                <div class="form-group row my-3 p-3">                  
                  <label for="{{ field.id_for_label }}">{{ field.label }}
                    {% if field.field.required %}
                    <span class="required text-danger" >*</span>
                    {% endif %}                    
                  </label>                  
                  {{ field }}                  
                </div>
              {% endfor %}                             
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if form.instance.id %}
                    Добавить
                  {% else %}
                    Сохранить
                  {% endif %}               
                </button>
              </div>
              <form/>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}    
  Последние обновления для подписчиков
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> Последние обновления авторов </h1>
    <article>
      {% include 'includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'includes/text.html' %}         
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
        {% endif %}          
        {% if not forloop.last %}<hr>{% endif %}        
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}   
  Записи сообщества: {{ group.title }}
{% endblock %} 

{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    <article>
      {% for post in page_obj %}
        {% include 'includes/text.html' %}
        {% if not forloop.last %}<hr>{% endif %}        
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}    
  {{ title }}
{% endblock %}

{% block content %}
{% load cache %}
{% cache 20 index_page page%}
  <div class="container py-5">
    <h1> {{ title }} </h1>
    <article>
      {% include 'includes/switcher.html' %}
      {% for post in page_obj %}
        {% include 'includes/text.html' %}         
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a>
        {% endif %}          
        {% if not forloop.last %}<hr>{% endif %}        
      {% endfor %}
      {% include 'includes/paginator.html' %}
    </article>
  </div>
{% endcache %}  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}    
  Пост {{ post|slice:':30' }}
{% endblock %}
  
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        <li class="list-group-item">
          Группа: {{ group }}
          <br>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          {% endif %}
        </li>
        <li class="list-group-item">
          Автор: {{ post.author }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: {{ post_count }} 
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
       {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
         <img class="card-img my-2" src="{{ im.url }}">
       {% endthumbnail %}
       <p>{{ post.text|linebreaks }}</p>
       {% if post.author == request.user %}       
       <a href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
       </a>
       {% endif %}            
    </article> 
    {% include 'includes/comment.html' %}     
  </div>  
{% endblock %}   

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}    
  Профайл пользователя {{ author }}
{% endblock %}

{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ post_count }} </h3>
    {% if user != author %}
      {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}   
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Группа: {{ post.group }}
          </li>  
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}      
        <p>{{ post|linebreaks }}</p>
        {% if post.group %} 
          <a href="{% url 'posts:group_list' post.group.slug %}"> все записи группы </a><br>
        {% endif %}
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>                
        {% if not forloop.last %}<hr>{% endif %}        
      {% endfor %}         
    </article>                   
    <hr>    
    {% include 'includes/paginator.html' %} 
  </div>
{% endblock %}